### ISSUE TITLE
Application Crashes When Resizing a Second Time

### ISSUE THREAD

**Issue by Bishmanrock** [Bishmanrock/BishEngine#27]
Issue: Initial resize works fine, but the second crashes the application

Error points to EngineMain.cs line 68 - Glfw.PollEvents();

Console gives error:

Process terminated. A callback was made on a garbage collected delegate of type 'Engine!GLFW.SizeCallback::Invoke'.
Repeat 2 times:
--------------------------------
   at GLFW.Glfw.PollEvents()
--------------------------------
   at Engine.EngineMain..ctor()
   at Sandbox..ctor()
   at Program.<Main>$(System.String[])

**Comment by Bishmanrock** [comment]
Issue resolved using ChatGPT, solution text:

The error message you're encountering, "A callback was made on a garbage collected delegate of type 'Engine!GLFW.SizeCallback::Invoke'", indicates that the delegate you assigned as the window resize callback is being garbage collected by .NET's memory management system. This typically happens when a delegate is created inline and not kept alive by a strong reference. When the garbage collector runs, it mistakenly thinks the delegate is no longer in use and collects it, leading to the crash on the subsequent resize event.

Here's how you can fix this issue:

1. Maintain a Strong Reference to the Delegate
You need to ensure that a strong reference to the delegate is maintained as long as it's needed. Instead of setting the callback inline, store it in a field of your class. This prevents the garbage collector from collecting the delegate prematurely.

For example:

csharp
Copy code
// Define the delegate field at the class level
private GLFW.SizeCallback _resizeCallback;

// In your setup or constructor
public YourClassConstructor()
{
    // Assign the delegate to the field
    _resizeCallback = new GLFW.SizeCallback(OnWindowSizeChanged);

    // Use the field to set the callback
    GLFW.SetWindowSizeCallback(window, _resizeCallback);
}

private void OnWindowSizeChanged(IntPtr window, int width, int height)
{
    // Your resize handling logic
}
By storing the delegate in a field (_resizeCallback), you ensure that it remains alive as long as your class instance is alive, preventing it from being garbage collected.
